/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.util.Calendar;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class FrSigno extends javax.swing.JFrame {

    /**
     * Creates new form FrSigno
     */
    public FrSigno() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        lbDia = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbResumo = new javax.swing.JLabel();
        lbResumo1 = new javax.swing.JLabel();
        lbResumo2 = new javax.swing.JLabel();
        lbResumo3 = new javax.swing.JLabel();
        rbCasado = new javax.swing.JRadioButton();
        rbSolteiro = new javax.swing.JRadioButton();
        rbSeparado = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbViuvo = new javax.swing.JRadioButton();
        lbEstadoCivil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MESTRE ZODI4CO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MESTRE DO ZODÍ4CO.com");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 20, 990, -1));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome ");
        jPanel1.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 750, 35));

        lbSexo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo");
        jPanel1.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        rbMasc.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbMasc.setForeground(new java.awt.Color(255, 255, 255));
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");
        rbMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMascActionPerformed(evt);
            }
        });
        jPanel1.add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        rbFem.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbFem);
        rbFem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbFem.setForeground(new java.awt.Color(255, 255, 255));
        rbFem.setText("Feminino");
        jPanel1.add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 120, -1));

        lbDia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDia.setForeground(new java.awt.Color(255, 255, 255));
        lbDia.setText("Dia");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lbMes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setText("Mês");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lbAno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAno.setForeground(new java.awt.Color(255, 255, 255));
        lbAno.setText("Ano");
        jPanel1.add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 150, 50));

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("/");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 20, 40));

        lbResumo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbResumo.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo.setText("Resumo:");
        jPanel1.add(lbResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        lbResumo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbResumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        lbResumo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbResumo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        lbResumo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbResumo3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbResumo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, -1, -1));

        rbCasado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbCasado);
        rbCasado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbCasado.setForeground(new java.awt.Color(255, 255, 255));
        rbCasado.setText("Casado(a)");
        jPanel1.add(rbCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 130, -1));

        rbSolteiro.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbSolteiro);
        rbSolteiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSolteiro.setForeground(new java.awt.Color(255, 255, 255));
        rbSolteiro.setSelected(true);
        rbSolteiro.setText("Solteiro(a)");
        jPanel1.add(rbSolteiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 130, -1));

        rbSeparado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbSeparado);
        rbSeparado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSeparado.setForeground(new java.awt.Color(255, 255, 255));
        rbSeparado.setText("Separado(a)");
        jPanel1.add(rbSeparado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 140, 30));

        rbDivorciado.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbDivorciado);
        rbDivorciado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbDivorciado.setForeground(new java.awt.Color(255, 255, 255));
        rbDivorciado.setText("Divorciado(a)");
        jPanel1.add(rbDivorciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 140, -1));

        rbViuvo.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(rbViuvo);
        rbViuvo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbViuvo.setForeground(new java.awt.Color(255, 255, 255));
        rbViuvo.setText("Viúvo(a)");
        jPanel1.add(rbViuvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 130, -1));

        lbEstadoCivil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        lbEstadoCivil.setText("Estado Cívil");
        jPanel1.add(lbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 90, 70));

        cbDia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        cbMes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });
        jPanel1.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        cbAno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cbAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnoActionPerformed(evt);
            }
        });
        jPanel1.add(cbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zodiaco1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        cbDia.setSelectedIndex(0);
        cbMes.setSelectedIndex(0);
        cbAno.setSelectedIndex(0);
        rbMasc.setSelected(true);
        rbSolteiro.setSelected(true);
        lbResumo1.setText(null);
        lbResumo2.setText(null);
        lbResumo3.setText(null);
        JOptionPane.showMessageDialog(null, "Sessão Finalizada!");
    }//GEN-LAST:event_btLimparActionPerformed
    public String nomearMes(int mes) {
        String mesNome = "";
        if (mes == 1) {
            mesNome = "Janeiro";
        } else if (mes == 2) {
            mesNome = "Fevereiro";
        } else if (mes == 3) {
            mesNome = "Março";
        } else if (mes == 4) {
            mesNome = "Abril";
        } else if (mes == 5) {
            mesNome = "Maio";
        } else if (mes == 6) {
            mesNome = "Junho";
        } else if (mes == 7) {
            mesNome = "Julho";
        } else if (mes == 8) {
            mesNome = "Agosto";
        } else if (mes == 9) {
            mesNome = "Setembro";
        } else if (mes == 10) {
            mesNome = "Outubro";
        } else if (mes == 11) {
            mesNome = "Novembro";
        } else if (mes == 12) {
            mesNome = "Dezembro";
        }
        return mesNome;
    }
    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        Calendar hoje = Calendar.getInstance();
        String nome, data, mesNome = "";
        int dia, mes, ano, nome2, num;
        int anoA = hoje.get(Calendar.YEAR), diaA = hoje.get(Calendar.DATE), mesA = hoje.get(Calendar.MONTH) + 1;

        int[] anos = {0, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909,
            1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919,
            1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929,
            1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939,
            1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949,
            1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
            1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969,
            1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
            1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
            2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
            2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
            2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030};

        nome = txtNome.getText();
        nome2 = nomear(nome);
        dia = cbDia.getSelectedIndex();
        mes = cbMes.getSelectedIndex();
        ano = anos[cbAno.getSelectedIndex()];

        if (mes == 4 && dia == 31) {
            JOptionPane.showMessageDialog(null, "O mês informado só tem 30 dias!");
        } else if (mes == 6 && dia == 31) {
            JOptionPane.showMessageDialog(null, "O mês informado só tem 30 dias!");
        } else if (mes == 9 && dia == 31) {
            JOptionPane.showMessageDialog(null, "O mês informado só tem 30 dias!");
        } else if (mes == 11 && dia == 31) {
            JOptionPane.showMessageDialog(null, "O mês informado só tem 30 dias!");
        } else if (mes == 2 && dia >= 29) {
            JOptionPane.showMessageDialog(null, "O mês informado só tem 28 dias!");
        } else if (ano > anoA) {
            JOptionPane.showMessageDialog(null, "Ano Inválido");
        } else if (ano == anoA && mes > mesA) {
            JOptionPane.showMessageDialog(null, "Mês Inválido");
        } else if (ano == anoA && mes == mesA && dia > diaA) {
            JOptionPane.showMessageDialog(null, "Dia Inválido");
        } else {
            lbResumo1.setText(fazerTratamento() + " " + nome + ", você nasceu dia " + dia + ", de " + nomearMes(mes) + ", de " + ano + ".");
            lbResumo2.setText("Você tem " + calcularIdade(dia, mes, ano) + " anos de idade.");
            lbResumo3.setText(nascer(dia, mes, ano) + ". Seu número da sorte é: " + gerarNum() + ". Sua cor é: " + gerarCor());
    }//GEN-LAST:event_btConsultarActionPerformed
    }
    private void rbMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMascActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void cbAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnoActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed
    public int nomear(String nome) {
        int cont = 0;
        cont = (nome.length());
        if (cont >= 8) {
            nome = txtNome.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Se esforça ai! Assim poderemos lhe oferecer melhores informações.");
        }
        return cont;
    }

    public String fazerTratamento() {
        String trato = "";
        if (rbMasc.isSelected()) {
            if (rbSolteiro.isSelected()) {
                trato = " ";
            } else {
                trato = "Sr.";
            }
        } else {
            if (rbSolteiro.isSelected()) {
                trato = "Srta.";
            } else {
                trato = "Sra.";
            }
        }
        return trato;
    }

    public String nascer(int dia, int mes, int ano) {
        String data = "";
        int diaA, mesA, anoA;
        Calendar hoje = Calendar.getInstance();

        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH) + 1;
        anoA = hoje.get(Calendar.YEAR);
        if (dia <= 0 || dia > 31 || mes <= 0 || mes > 12 || ano < 1900 || ano > anoA) {
            JOptionPane.showMessageDialog(null, "Dia, mes ou ano invalido!!");
        } else {
            if (mes == 3 && dia >= 21 && dia <= 31) {
                data = "Você é do signo Áries";
            } else if (mes == 4 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Áries";
            } else if (mes == 4 && dia >= 21 && dia <= 30) {
                data = "Você é do signo Touro";
            } else if (mes == 5 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Touro";
            } else if (mes == 5 && dia >= 21 && dia <= 31) {
                data = "Você é do signo Gemêos";
            } else if (mes == 6 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Gemêos";
            } else if (mes == 6 && dia >= 21 && dia <= 30) {
                data = "Você é do signo Câncer";
            } else if (mes == 7 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Câncer";
            } else if (mes == 7 && dia >= 22 && dia <= 31) {
                data = "Você é do signo Leão";
            } else if (mes == 8 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Leão";
            } else if (mes == 8 && dia >= 23 && dia <= 31) {
                data = "Você é do signo Virgem";
            } else if (mes == 9 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Virgem";
            } else if (mes == 9 && dia >= 23 && dia <= 30) {
                data = "Você é do signo Libra";
            } else if (mes == 10 && dia >= 1 && dia <= 22) {
                data = "Você é do signo Libra";
            } else if (mes == 10 && dia >= 23 && dia <= 31) {
                data = "Você é do signo Escorpião";
            } else if (mes == 11 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Escorpião";
            } else if (mes == 11 && dia >= 22 && dia <= 30) {
                data = "Você é do signo Sagitário";
            } else if (mes == 12 && dia >= 1 && dia <= 21) {
                data = "Você é do signo Sagitário";
            } else if (mes == 12 && dia >= 22 && dia <= 31) {
                data = "Você é do signo Capricórnio";
            } else if (mes == 1 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Capricórnio";
            } else if (mes == 1 && dia >= 21 && dia <= 31) {
                data = "Você é do signo AquarianoNato";
            } else if (mes == 2 && dia >= 1 && dia <= 19) {
                data = "Você é do signo AquarianoNato";
            } else if (mes == 2 && dia >= 20 && dia <= 28) {
                data = "Você é do signo Peixes";
            } else if (mes == 3 && dia >= 1 && dia <= 20) {
                data = "Você é do signo Peixes";
            }
        }
        return data;
    }

    public int gerarNum() {
        int n;
        n = (int) (Math.random() * 12) + 1;
        return n;
    }

    public String gerarCor() {
        String corAleatoria;
        String[] cor = {"Verde", "Azul", "Roxo", "Vermelho", "Amarelo", "Rosa", "Preto", "Branco", "Laranja", "Marrom", "Cinza", "Violeta"};
        Random randomCor = new Random();
        int vet = cor.length;
        int i = randomCor.nextInt(vet);
        String cores = cor[i];
        return cores;
    }

    public int calcularIdade(int dia, int mes, int ano) {
        int idade;
        int diaA, mesA, anoA;
        Calendar hoje = Calendar.getInstance();

        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH) + 1;
        anoA = hoje.get(Calendar.YEAR);
        idade = ((anoA * 365 + mesA * 12 + diaA) - (ano * 365 + mes * 12 + dia)) / 365;

        return idade;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSigno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSigno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbEstadoCivil;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbResumo;
    private javax.swing.JLabel lbResumo1;
    private javax.swing.JLabel lbResumo2;
    private javax.swing.JLabel lbResumo3;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbSeparado;
    private javax.swing.JRadioButton rbSolteiro;
    private javax.swing.JRadioButton rbViuvo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
